### ISSUE TITLE
Dragonfly replica crash

### ISSUE THREAD

**Issue by vladimirem93** [dragonflydb/dragonfly#2500]
**Describe the bug**
Replica crashes unexpectedly, reasons for replica to die weren't detected

**To Reproduce**
350 mln non-expiring keys 
used_memory_human:57.30GiB
maxmemory_human:250.00GiB
Commands executed per second 20 000 ops
Most commonly used operation: hget, hset
Most commonly used strucuture: HashMap

**Expected behavior**
Stable condition

**Environment (please complete the following information):**
 - OS: bullseye/sid (container)  Rhel 9 (Host)
 - Kernel: 5.14.0-284.30.1.el9_2.x86_64 
 - Containerized?: Docker
 - Dragonfly Version: 1.12.0
 - Build Image: FROM docker.dragonflydb.io/dragonflydb/dragonfly:v1.12.0 

* Configuration info 
dragonfly --logtostderr --port 6379 --maxmemory=50G --dir $DRAGONFLY_DATA_DIR --requirepass=<password> --cache_mode=true --snapshot_cron "* */1 * * *" --dbnum 100 --masterauth=<password> --dbfilename dump

sh -c dragonfly --logtostderr --port $DRAGONFLY_PORT --maxmemory=$DRAGONFLY_MEMORY \ 
--dir $DRAGONFLY_DATA_DIR --requirepass=$DRAGONFLY_MASTER_PASSWORD --cache_mode=true \ 
--snapshot_cron "$DRAGONFLY_CRON_SCHEDULE" --dbnum 100 --masterauth=$DRAGONFLY_MASTER_PASSWORD \
--dbfilename $DRAGONFLY_DUMP_FILENAME

dragonfly:
    image: dp-dragonflydb/dragonflydb:v.1.13.0
    network_mode: "host"
    restart: always
    ulimits:
      memlock: -1
    environment:
      <<: *dragonfy-environment
      DRAGONFLY_PORT: <PORT>
      DRAGONFLY_MEMORY: 50G
      DRAGONFLY_MASTER_PASSWORD: <PASSWORD>
      DRAGONFLY_DUMP_FILENAME: dump
    volumes:
      - $DATA_DIR/dragonfly:/data/dragonfly
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          memory: 60G
          cpus: '60'
    oom_kill_disable: true
    memswap_limit: 60G 

**Additional context**

Logs before crash: 

I20240129 03:03:43.669939    23 dflycmd.cc:385] Transitioned into stable sync with replica 10.44.73.10:6397
I20240129 03:25:03.809696    12 save_stages_controller.cc:276] Saving "/data/dragonfly/dump-summary.dfs" finished after 3.81 s
I20240129 03:50:04.580170    12 save_stages_controller.cc:276] Saving "/data/dragonfly/dump-summary.dfs" finished after 4.58 s
I20240129 04:00:19.486539    25 dflycmd.cc:614] Replication error: Software caused connection abort
I20240129 04:00:19.492048    31 dflycmd.cc:663] Disconnecting from replica 10.44.73.10:6397
I20240129 04:00:24.963119    12 save_stages_controller.cc:276] Saving "/data/dragonfly/dump-summary.dfs" finished after 25 s 
I20240129 03:35:01.495014    12 save_stages_controller.cc:276] Saving "/data/dragonfly/dump-summary.dfs" finished after 1.49 s
I20240129 04:00:09.446189    12 save_stages_controller.cc:276] Saving "/data/dragonfly/dump-summary.dfs" finished after 9.44 s
I20240129 04:00:17.317588    13 server_family.cc:1937] Replicating NO:ONE
I20240129 04:00:17.319891     9 replica.cc:636] Exit stable sync
W20240129 04:00:17.319902     9 replica.cc:237] Error stable sync with 10.14.205.15:6397 generic:125 Operation canceled
E20240129 04:00:17.322391    13 server_family.cc:1246] Subcommand KILL not supported
E20240129 04:00:17.322402    13 server_family.cc:1246] Subcommand KILL not supported

**Comment by vladimirem93** [comment]
Additional logs: 

F20240112 10:00:26.121748    12 hset_family.cc:1205] Check failed: sm->AddOrUpdate(key, value) 
*** Check failure stack trace: ***
    @     0x55c4056f19f3  google::LogMessage::SendToLog()
    @     0x55c4056ea1b7  google::LogMessage::Flush()
    @     0x55c4056ebb3f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55c404da44d0  dfly::HSetFamily::ConvertToStrMap()
    @     0x55c404da4bd2  dfly::(anonymous namespace)::OpSet()
    @     0x55c404da4d58  _ZN4absl12lts_2023080219functional_internal12InvokeObjectIZN4dfly11Transaction18ScheduleSingleHopTIZNS3_10HSetFamily4HSetENS0_4SpanINS7_IcEEEEPNS3_17ConnectionContextEEUlPS4_PNS3_11EngineShardEE_EEDTclfp_fpTLDn0EEEOT_EUlSC_SE_E_N6facade8OpStatusEJSC_SE_EEET0_NS1_7VoidPtrEDpNS1_8ForwardTIT1_E4typeE
    @     0x55c4050047b6  dfly::Transaction::RunQuickie()
    @     0x55c40500494e  dfly::Transaction::ScheduleUniqueShard()
    @     0x55c405006130  dfly::Transaction::ScheduleSingleHop()
    @     0x55c404d9f95f  dfly::HSetFamily::HSet()
    @     0x55c404f3595e  dfly::CommandId::Invoke()
    @     0x55c404e15329  dfly::Service::InvokeCmd()
    @     0x55c404e1993d  dfly::Service::DispatchCommand()
    @     0x55c40500dbaf  dfly::JournalExecutor::Execute()
    @     0x55c404fcc1b9  dfly::DflyShardReplica::ExecuteTx()
    @     0x55c404fd020e  dfly::DflyShardReplica::StableSyncDflyReadFb()
    @     0x55c404fd1bd1  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberENS0_21basic_fixedsize_stackINS0_12stack_traitsEEEZN4util3fb26detail15WorkerFiberImplIMN4dfly16DflyShardReplicaEFvPNSC_7ContextEEJPSD_RSF_EEC4IS7_EESt17basic_string_viewIcSt11char_traitsIcEERKNS0_12preallocatedEOT_OSH_OSI_SJ_EUlOS4_E_EEEEvNS1_10transfer_tE
    @     0x55c40550efaf  make_fcontext
*** SIGABRT received at time=1705053626 on cpu 3 ***
PC: @     0x7fe1177e700b  (unknown)  raise
Aborted (core dumped)




2024-01-21T09:00:22.539908596Z I20240121 09:00:22.539773    14 save_stages_controller.cc:285] Saving "/data/dragonfly/dump-summary.dfs" finished after 22.5 s
2024-01-21T09:25:04.310404150Z *** SIGSEGV received at time=1705829104 on cpu 53 ***
2024-01-21T09:25:04.312406424Z PC: @     0x55b7d5660e68  (unknown)  dfly::SliceSnapshot::OnDbChange()
2024-01-21T09:26:20.170675311Z Segmentation fault (core dumped)
2024-01-21T09:26:20.354727130Z I20240121 09:26:20.354629     8 init.cc:70] dragonfly running in opt mode.
2024-01-21T09:26:20.354756744Z I20240121 09:26:20.354688     8 dfly_main.cc:800] Starting dragonfly df-v1.12.0-e46dd24bb7273a5ef25e8d12b54a9d53979d7121
2024-01-21T09:26:20.354767721Z * Logs will be written to the first available of the following paths:
2024-01-21T09:26:20.354794361Z /tmp/dragonfly.*
2024-01-21T09:26:20.354796464Z ./dragonfly.*

**Comment by romange** [comment]
@vladimirem93  thank youf for reporting this.
1. does it happen frequently? 
2. I would like to build a special version that will identify the root cause of this. Will you be able to try it out?

**Comment by romange** [comment]
The following build https://github.com/dragonflydb/dragonfly/actions/runs/7699991505 will finish in a few hours. 
Once it completes successfully, I will update which tag from https://github.com/dragonflydb/dragonfly/pkgs/container/dragonfly-weekly should be used to deploy the server.

**Comment by romange** [comment]
@vladimirem93 
Please use this build for the following checks: `docker pull ghcr.io/dragonflydb/dragonfly-weekly:b561c25b1b828ebd95d86cce95bac8c837647276-ubuntu`

**Comment by vladimirem93** [comment]
@romange 
Got it. Thank you!

**Comment by vladimirem93** [comment]
@romange Roman, sorry, this build is purposed to fix our problem, did I understand it right?

**Comment by romange** [comment]
nope, it won't solve the problem. It will help us to identify the root cause of the problem. Once we identify, we will issue the correct fix.

**Comment by vladimirem93** [comment]
Oh right. I see. I just had to clarify one more time. 
Could you please also explain how exactly we will see the root cause, the build will show additional logs?

**Comment by romange** [comment]
yeah, you can see them here: https://github.com/dragonflydb/dragonfly/commit/b561c25b1b828ebd95d86cce95bac8c837647276

**Comment by vladimirem93** [comment]
@romange hello. Today we deployed the special build you've prepared for us. 
About 2 hours later after the deploy we got the following problem. We guess it caused by some network trouble. 
Could you please share your thoughts regarding to this? 

I20240131 03:53:54.165887     8 dfly_main.cc:686] Max memory limit is: 100.00GiB
W20240131 03:53:54.165897     8 dfly_main.cc:343] iouring API is not supported. switching to epoll.
I20240131 03:53:54.244104     8 proactor_pool.cc:146] Running 60 io threads
I20240131 03:53:54.249446     8 server_family.cc:644] Host OS: Linux 5.14.0-284.30.1.el9_2.x86_64 x86_64 with 60 threads
I20240131 03:53:54.268255     8 snapshot_storage.cc:108] Load snapshot: Searching for snapshot in directory: "/data/dragonfly"
W20240131 03:53:54.268318     8 server_family.cc:737] Load snapshot: No snapshot found
I20240131 03:53:54.268592    10 listener_interface.cc:101] sock[123] AcceptServer - listening on port 6397
E20240131 03:53:59.171988    33 server_family.cc:2399] Subcommand HISTOGRAM not supported
E20240131 03:54:04.169318    35 server_family.cc:2399] Subcommand HISTOGRAM not supported
I20240131 03:54:04.442739     9 server_family.cc:2123] Replicating 10.44.73.10:6397
I20240131 03:54:04.467902     9 replica.cc:515] Started full sync with 10.44.73.10:6397
E20240131 03:54:09.172475    36 server_family.cc:2399] Subcommand HISTOGRAM not supported
E20240131 03:54:14.170799    37 server_family.cc:2399] Subcommand HISTOGRAM not supported
I20240131 03:54:14.576849     9 replica.cc:535] full sync finished in 10.1 s
I20240131 03:54:14.584177     9 replica.cc:605] Transitioned into stable sync
E20240131 03:54:19.175922    38 server_family.cc:2399] Subcommand HISTOGRAM not supported
E20240131 03:54:24.168855    39 server_family.cc:2399] Subcommand HISTOGRAM not supported
E20240131 03:54:29.169315    41 server_family.cc:2399] Subcommand HISTOGRAM not supported
E20240131 03:54:34.175709    42 server_family.cc:2399] Subcommand HISTOGRAM not supported
E20240131 03:54:39.169904    43 server_family.cc:2399] Subcommand HISTOGRAM not supported
E20240131 03:54:44.172294    44 server_family.cc:2399] Subcommand HISTOGRAM not supported
I20240131 04:00:24.613888    12 save_stages_controller.cc:283] Saving "/data/dragonfly/dump-summary.dfs" finished after 24 s
I20240131 04:32:04.275810    12 save_stages_controller.cc:283] Saving "/data/dragonfly/dump-summary.dfs" finished after 4 s

**Comment by romange** [comment]
what's the problem?

**Comment by vladimirem93** [comment]
Roman, I apologize, I didn't send you the full logs, below is the first part of logs. 
The problem is replica lost it's master. 

E20240131 03:53:24.600561     9 replica.cc:191] Error connecting to 10.14.205.15:6397 system:111
E20240131 03:53:25.100978     9 replica.cc:191] Error connecting to 10.14.205.15:6397 system:111
E20240131 03:53:25.602008     9 replica.cc:191] Error connecting to 10.14.205.15:6397 system:111
E20240131 03:53:26.103267     9 replica.cc:191] Error connecting to 10.14.205.15:6397 system:111
E20240131 03:53:26.604420     9 replica.cc:191] Error connecting to 10.14.205.15:6397 system:111
E20240131 03:53:27.104859     9 replica.cc:191] Error connecting to 10.14.205.15:6397 system:111
E20240131 03:53:27.605506     9 replica.cc:191] Error connecting to 10.14.205.15:6397 system:111
E20240131 03:53:28.106696     9 replica.cc:191] Error connecting to 10.14.205.15:6397 system:111
E20240131 03:53:28.607244     9 replica.cc:191] Error connecting to 10.14.205.15:6397 system:111
E20240131 03:53:29.107959     9 replica.cc:191] Error connecting to 10.14.205.15:6397 system:111
E20240131 03:53:29.608387     9 replica.cc:191] Error connecting to 10.14.205.15:6397 system:111
E20240131 03:53:30.109652     9 replica.cc:191] Error connecting to 10.14.205.15:6397 system:111
E20240131 03:53:30.610874     9 replica.cc:191] Error connecting to 10.14.205.15:6397 system:111
E20240131 03:53:31.111424     9 replica.cc:191] Error connecting to 10.14.205.15:6397 system:111
E20240131 03:53:31.612210     9 replica.cc:191] Error connecting to 10.14.205.15:6397 system:111
I20240131 03:53:31.887681    11 server_family.cc:2123] Replicating NO:ONE
E20240131 03:53:32.113184     9 replica.cc:191] Error connecting to 10.14.205.15:6397 generic:125
I20240131 03:54:04.452888    20 dflycmd.cc:562] Registered replica 10.14.205.15:6397
I20240131 03:54:04.466702    20 dflycmd.cc:281] Started sync with replica 10.14.205.15:6397
I20240131 03:54:14.576669    20 dflycmd.cc:319] Transitioned into stable sync with replica 10.14.205.15:6397
I20240131 04:00:26.483053    12 save_stages_controller.cc:283] Saving "/data/dragonfly/dump-summary.dfs" finished after 26 s
I20240131 04:20:08.566308    12 save_stages_controller.cc:283] Saving "/data/dragonfly/dump-summary.dfs" finished after 8 s

**Comment by romange** [comment]
Yes, seems that there was an prod-event there. It's hard to judge exactly what happened. What replica logs are showing?

**Comment by vladimirem93** [comment]
Hello Roman, I am sorry for the delayed answer. My apologies, no need to check this problem for now. Probably caused by our local network loss problem. 

As soon as we get replica crash we will report to you! 

We are really appreciate your help! 
Thanks.

**Comment by vladimirem93** [comment]
Hello @romange 

Now we got the replica crashed twice in a row on the host with special build. 
Please find the logs below: 

`I20240202 10:00:29.053778    12 save_stages_controller.cc:283] Saving "/data/dragonfly/dump-summary.dfs" finished after 29 s
I20240202 10:01:53.468426    67 dflycmd.cc:601] Disconnecting from replica <IP>:6397
I20240202 10:01:53.468569    67 dflycmd.cc:552] Replication error: Operation canceled: Context cancelled
I20240202 10:02:17.752771    23 dflycmd.cc:562] Registered replica <IP>:6397
I20240202 10:02:17.848536    23 dflycmd.cc:281] Started sync with replica <IP>:6397
F20240202 10:02:17.938508    59 db_slice.cc:341] Check failed: fields_.db_size == fields_.db_slice->DbSize(fields_.db_ind) (188153 vs. 188145) Attempting to run post-update after DB was modified
*** Check failure stack trace: ***
    @     0x56163cdc09f3  google::LogMessage::SendToLog()
    @     0x56163cdb91b7  google::LogMessage::Flush()
F20240202 10:02:17.941182    19 db_slice.cc:341] Check failed: fields_.db_size == fields_.db_slice->DbSize(fields_.db_ind) (1602430 vs. 1602429) Attempting to run post-update after DB was modified
*** Check failure stack trace: ***
    @     0x56163cdbab3f  google::LogMessageFatal::~LogMessageFatal()
    @     0x56163cdc09f3  google::LogMessage::SendToLog()
    @     0x56163c68c21c  dfly::DbSlice::AutoUpdater::Run()
    @     0x56163cdb91b7  google::LogMessage::Flush()
    @     0x56163cdbab3f  google::LogMessageFatal::~LogMessageFatal()
    @     0x56163c68c47d  dfly::DbSlice::AutoUpdater::~AutoUpdater()
    @     0x56163c68c21c  dfly::DbSlice::AutoUpdater::Run()
    @     0x56163c583e69  dfly::SetCmd::Set()
    @     0x56163c68c47d  dfly::DbSlice::AutoUpdater::~AutoUpdater()
    @     0x56163c584ac8  _ZN4absl12lts_2023080219functional_internal12InvokeObjectIZN4dfly12StringFamily12SetExGenericEbNS0_4SpanINS5_IcEEEEPNS3_17ConnectionContextEEUlPNS3_11TransactionEPNS3_11EngineShardEE_NSA_14RunnableResultEJSB_SD_EEET0_NS1_7VoidPtrEDpNS1_8ForwardTIT1_E4typeE
    @     0x56163c583e69  dfly::SetCmd::Set()
    @     0x56163c584ac8  _ZN4absl12lts_2023080219functional_internal12InvokeObjectIZN4dfly12StringFamily12SetExGenericEbNS0_4SpanINS5_IcEEEEPNS3_17ConnectionContextEEUlPNS3_11TransactionEPNS3_11EngineShardEE_NSA_14RunnableResultEJSB_SD_EEET0_NS1_7VoidPtrEDpNS1_8ForwardTIT1_E4typeE
    @     0x56163c6bca34  dfly::Transaction::RunQuickie()
    @     0x56163c6bca34  dfly::Transaction::RunQuickie()
    @     0x56163c6bebbe  dfly::Transaction::ScheduleUniqueShard()
    @     0x56163c6bebbe  dfly::Transaction::ScheduleUniqueShard()
    @     0x56163c6c2e0b  _ZNSt17_Function_handlerIFvvEZN4dfly11Transaction17ScheduleSingleHopEN4absl12lts_2023080211FunctionRefIFNS2_14RunnableResultEPS2_PNS1_11EngineShardEEEEEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x56163c6c2e0b  _ZNSt17_Function_handlerIFvvEZN4dfly11Transaction17ScheduleSingleHopEN4absl12lts_2023080211FunctionRefIFNS2_14RunnableResultEPS2_PNS1_11EngineShardEEEEEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x56163c6f97b0  dfly::TaskQueue::TaskLoop()
    @     0x56163c6f97b0  dfly::TaskQueue::TaskLoop()
    @     0x56163c6f9c10  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberENS0_21basic_fixedsize_stackINS0_12stack_traitsEEEZN4util3fb26detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEEC4IS7_EESH_RKNS0_12preallocatedEOT_OSI_EUlOS4_E_EEEEvNS1_10transfer_tE
    @     0x56163c6f9c10  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberENS0_21basic_fixedsize_stackINS0_12stack_traitsEEEZN4util3fb26detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEEC4IS7_EESH_RKNS0_12preallocatedEOT_OSI_EUlOS4_E_EEEEvNS1_10transfer_tE
    @     0x56163cbdd32f  make_fcontext
    @     0x56163cbdd32f  make_fcontext
[failure_signal_handler.cc : 345] RAW: Signal 6 raised at PC=0x7f24ca13000b while already in AbslFailureSignalHandler()
*** SIGABRT received at time=1706868137 on cpu 50 ***
PC: @     0x7f24ca13000b  (unknown)  raise
Aborted (core dumped)
I20240202 10:03:31.918756     8 init.cc:70] dragonfly running in opt mode.
I20240202 10:03:31.918823     8 dfly_main.cc:623] Starting dragonfly df-b561c25-b561c25b1b828ebd95d86cce95bac8c837647276
* Logs will be written to the first available of the following paths:
/tmp/dragonfly.*
./dragonfly.*
* For the available flags type dragonfly [--help | --helpfull]
* Documentation can be found at: https://www.dragonflydb.io/docs
W20240202 10:03:31.918957     8 dfly_main.cc:662] SWAP is enabled. Consider disabling it when running Dragonfly.
I20240202 10:03:31.918975     8 dfly_main.cc:686] Max memory limit is: 100.00GiB
W20240202 10:03:31.918989     8 dfly_main.cc:343] iouring API is not supported. switching to epoll.
I20240202 10:03:31.997236     8 proactor_pool.cc:146] Running 60 io threads
I20240202 10:03:32.003664     8 server_family.cc:644] Host OS: Linux 5.14.0-284.30.1.el9_2.x86_64 x86_64 with 60 threads
I20240202 10:03:32.020344     8 snapshot_storage.cc:108] Load snapshot: Searching for snapshot in directory: "/data/dragonfly"
I20240202 10:03:32.020742     8 server_family.cc:807] Loading /data/dragonfly/dump-summary.dfs
`

**Comment by romange** [comment]
Thank you for reporting. It's a different bug and we are looking into it.

**Comment by romange** [comment]
@vladimirem93  I see only one instance of logs. Do you have logs from the second failure?

**Comment by chakaz** [comment]
@vladimirem93 hey there!
Regarding the last crash you reported in https://github.com/dragonflydb/dragonfly/issues/2500#issuecomment-1923507450
You've mentioned that you use *non expiring keys*, is that exclusively (i.e. all keys are non-expiring)?
We can think of an explanation for this crash if there are expiring keys, but since you explicitly mentioned that, perhaps that's not it?

**Comment by chakaz** [comment]
Actually, it looks like the crash is happening inside either `SETEX` or `PSETEX` (they use the same implementation), so it's very likely to be related to expiration

**Comment by chakaz** [comment]
Please ignore the above messages, we've found the issue. Thanks again for the report, we're working on a fix.

**Comment by vladimirem93** [comment]
> @vladimirem93 I see only one instance of logs. Do you have logs from the second failure?

Sorry, I think the logs aren't avialable anymore. As soon as the crash happens I will request logs from the both failures.

**Comment by vladimirem93** [comment]
hello @chakaz ! 
ok, no worries. 
Please don't hesitate to ask anything you need. 

Thank you

**Comment by vladimirem93** [comment]
Hello @romange @chakaz 
May I ask will this problem be fixed in the newer version of dragonfly or it will be a special build? 

Thank you ! : )

**Comment by romange** [comment]
@vladimirem93  please upgrade to `ghcr.io/dragonflydb/dragonfly-weekly:2a8540686c940a4088cd1a83c6ec91dbadd74dbd-ubuntu` which fixes the second issue. The first crash is still under the investigation

**Comment by vladimirem93** [comment]
@romange yesterday we upgraded dragonfly. Thank you! 

Unfortunately, before the upgrade we got the problem, when our devops engineer tried to change bgsave cron interval and to restart the instance. Is it the same issue that you already fixed or something else?  

Please find the logs below: 


I20240207 12:59:02.730321    46 dflycmd.cc:281] Started sync with replica 10.44.73.10:6397
F20240207 12:59:02.886190    25 db_slice.cc:341] Check failed: fields_.db_size == fields_.db_slice->DbSize(fields_.db_ind) (1272606 vs. 1272605) Attempting to run post-update after DB was modified
*** Check failure stack trace: ***
    @     0x555aff63e9f3  google::LogMessage::SendToLog()
    @     0x555aff6371b7  google::LogMessage::Flush()
    @     0x555aff638b3f  google::LogMessageFatal::~LogMessageFatal()
    @     0x555afef0a21c  dfly::DbSlice::AutoUpdater::Run()
    @     0x555afef0a47d  dfly::DbSlice::AutoUpdater::~AutoUpdater()
    @     0x555afee01e69  dfly::SetCmd::Set()
    @     0x555afee02ac8  _ZN4absl12lts_2023080219functional_internal12InvokeObjectIZN4dfly12StringFamily12SetExGenericEbNS0_4SpanINS5_IcEEEEPNS3_17ConnectionContextEEUlPNS3_11TransactionEPNS3_11EngineShardEE_NSA_14RunnableResultEJSB_SD_EEET0_NS1_7VoidPtrEDpNS1_8ForwardTIT1_E4typeE
    @     0x555afef3aa34  dfly::Transaction::RunQuickie()
    @     0x555afef3cbbe  dfly::Transaction::ScheduleUniqueShard()
    @     0x555afef40e0b  _ZNSt17_Function_handlerIFvvEZN4dfly11Transaction17ScheduleSingleHopEN4absl12lts_2023080211FunctionRefIFNS2_14RunnableResultEPS2_PNS1_11EngineShardEEEEEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x555afef777b0  dfly::TaskQueue::TaskLoop()
    @     0x555afef77c10  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberENS0_21basic_fixedsize_stackINS0_12stack_traitsEEEZN4util3fb26detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEEC4IS7_EESH_RKNS0_12preallocatedEOT_OSI_EUlOS4_E_EEEEvNS1_10transfer_tE
    @     0x555aff45b32f  make_fcontext
*** SIGABRT received at time=1707310742 on cpu 16 ***
PC: @     0x7f641d6a300b  (unknown)  raise


-----


F20240207 13:02:25.122699    65 db_slice.cc:341] Check failed: fields_.db_size == fields_.db_slice->DbSize(fields_.db_ind) (1488731 vs. 1488730) Attempting to run post-update after DB was modified
*** Check failure stack trace: ***
    @     0x55e1bb33c9f3  google::LogMessage::SendToLog()
    @     0x55e1bb3351b7  google::LogMessage::Flush()
    @     0x55e1bb336b3f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55e1bac0821c  dfly::DbSlice::AutoUpdater::Run()
    @     0x55e1bac0847d  dfly::DbSlice::AutoUpdater::~AutoUpdater()
    @     0x55e1baaffe69  dfly::SetCmd::Set()
    @     0x55e1bab00ac8  _ZN4absl12lts_2023080219functional_internal12InvokeObjectIZN4dfly12StringFamily12SetExGenericEbNS0_4SpanINS5_IcEEEEPNS3_17ConnectionContextEEUlPNS3_11TransactionEPNS3_11EngineShardEE_NSA_14RunnableResultEJSB_SD_EEET0_NS1_7VoidPtrEDpNS1_8ForwardTIT1_E4typeE
    @     0x55e1bac38a34  dfly::Transaction::RunQuickie()
    @     0x55e1bac3abbe  dfly::Transaction::ScheduleUniqueShard()
    @     0x55e1bac3ee0b  _ZNSt17_Function_handlerIFvvEZN4dfly11Transaction17ScheduleSingleHopEN4absl12lts_2023080211FunctionRefIFNS2_14RunnableResultEPS2_PNS1_11EngineShardEEEEEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x55e1bac757b0  dfly::TaskQueue::TaskLoop()
    @     0x55e1bac75c10  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberENS0_21basic_fixedsize_stackINS0_12stack_traitsEEEZN4util3fb26detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEEC4IS7_EESH_RKNS0_12preallocatedEOT_OSI_EUlOS4_E_EEEEvNS1_10transfer_tE
    @     0x55e1bb15932f  make_fcontext
*** SIGABRT received at time=1707310945 on cpu 56 ***
PC: @     0x7f7afdc5e00b  (unknown)  raise

**Comment by romange** [comment]
Yes, it's been fixed @vladimirem93

**Comment by vladimirem93** [comment]
@romange okay, thank you ! 

I apologize for the offtop. We are also facing the problem with latency growth during bgsave process. Latency on read operations(hget, hset) is up to 2000ms. 
![image](https://github.com/dragonflydb/dragonfly/assets/12939897/7566a913-58d0-4c3c-9692-bbb1e6edbe8c)

Could you please give some advice on how to configure bgsave process for master and replica so it won't be executinf simultaneously? 

We tried to configure different intervals, hovewer it happens at the same time. 
'master': '2024-02-08 13:00:00',
'slave': '2024-02-08 13:00:00'

Thank you!

**Comment by romange** [comment]
what's your `snapshot_cron` argument?
@vladimirem93  DM'ed you on discord

**Comment by vladimirem93** [comment]
@romange  okay! will be there in a minute

**Comment by chakaz** [comment]
@romange assigning to you to look into the other crash, as it seems you and @vladimirem93 took things offline. Please let me know if I can help in any way still.

**Comment by romange** [comment]
@vladimirem93  have you experiences any more crashes with the updated version?

**Comment by vladimirem93** [comment]
hello
@romange
No, we haven't. 
I think the initial problem is fixed for now. Shall I close the issue?

**Comment by romange** [comment]
There is nothing much we can do unfortunately until we have more info regarding the crash. 
Feel free to reopen issue if you get more logs during the failure

**Comment by vladimirem93** [comment]
@romange 
Okay. 
And again, we are really pleased to have your help. Thank you!
